### PR TITLE
add godep to use dependencies/revision

### PR DESCRIPTION
**Pull request by odacremolbap**
Add godep, linking gherkin-go on 0c0f2d933220a0ebc0dd5e35d7c73dd5b4968d85 commit to workaround #17 

Test dependencies not included automatically in godep.
```/github.com/go-sql-driver/mysql```should be added manually

### CODE REVIEW

**Comment by odacremolbap** [comment]
Travis is failing because it's executing `go get github.com/cucumber/gherkin-go`
I'm fixing that one bringing godep to `.travis.yml`

**Comment by l3pp4rd** [comment]
as a temporary solution I'd rather change it to gopkg.in/cucumber/gherkin-go.v3 which would explicitly require a release version, instead of introducing godeps. gherkin-go may make a release under v3 with backward incompatible changes, in that case adapting source code would be necessary

**Comment by odacremolbap** [comment]
Great. I'll take a look into it, but I don't think I have time to change that at this moment.

**Comment by odacremolbap** [comment]
OK, it's working now.
Thanks!

**Pull request closed without merging**
